//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLC.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLC.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ADRES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ANASAYFA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AYARLAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Ayarlar {
            get {
                return ResourceManager.GetString("Ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlanıyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Baglaniyor {
            get {
                return ResourceManager.GetString("Baglaniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlantı Yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BaglantiYok {
            get {
                return ResourceManager.GetString("BaglantiYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇIKIŞ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Deger {
            get {
                return ResourceManager.GetString("Deger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DEĞİŞTİR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Degistir {
            get {
                return ResourceManager.GetString("Degistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GİRİŞ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GRAFİK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Grafik {
            get {
                return ResourceManager.GetString("Grafik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP ADRESİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IpAdresi {
            get {
                return ResourceManager.GetString("IpAdresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İsim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string İsim {
            get {
                return ResourceManager.GetString("İsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Milisaniye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MiliSaniye {
            get {
                return ResourceManager.GetString("MiliSaniye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC AYARLARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlcAyar {
            get {
                return ResourceManager.GetString("PlcAyar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ŞİFRE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TÜMÜNÜ SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TumunuSil {
            get {
                return ResourceManager.GetString("TumunuSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YAZILABİLİR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Yazilabilir {
            get {
                return ResourceManager.GetString("Yazilabilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YAZMA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Yazma {
            get {
                return ResourceManager.GetString("Yazma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zaman benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Zaman {
            get {
                return ResourceManager.GetString("Zaman", resourceCulture);
            }
        }
    }
}
